server:
  port: 8080
  undertow:
    threads:
      io: 4
      worker: 30
    buffer-size: 1024
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

custom:
  service:
    repo-strategy:
      default-strategy: j_final_repo_strategy
      lucene:
        root-path: E:/lucene
        clear-when-start: true
    cache-strategy:
      enable: true
      default-strategy: redis_strategy
      clear-when-start: false
      cache-timeout-seconds: 3600
  api:
    response:
      key-of-error-code: error
      key-of-error-message: message
      key-of-data: message
    static-sources:
      - /*.html
      - /**/*.html
      - /**/*.css
      - /**/*.js